"""empty message

Revision ID: b60bb575bb9a
Revises: e177ae92c305
Create Date: 2021-03-24 01:52:35.417228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b60bb575bb9a'
down_revision = 'e177ae92c305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_ibfk_1', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_ibfk_1', 'transactions', 'books', ['book_id'], ['id'])
    # ### end Alembic commands ###
