"""empty message

Revision ID: bf15b9bd23b8
Revises: b60bb575bb9a
Create Date: 2021-03-24 01:58:27.316608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf15b9bd23b8'
down_revision = 'b60bb575bb9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_ibfk_2', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'members', ['member_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_ibfk_2', 'transactions', 'members', ['member_id'], ['id'])
    # ### end Alembic commands ###
