"""empty message

Revision ID: c4d8b1f90e9d
Revises: c06d3d1bc271
Create Date: 2021-03-14 18:18:39.661689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d8b1f90e9d'
down_revision = 'c06d3d1bc271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('dob', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'dob')
    # ### end Alembic commands ###
