"""empty message

Revision ID: e177ae92c305
Revises: 38c7f4782de7
Create Date: 2021-03-20 17:18:06.915384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e177ae92c305'
down_revision = '38c7f4782de7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'fee')
    op.add_column('transactions', sa.Column('fee', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'fee')
    op.add_column('members', sa.Column('fee', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
