"""empty message

Revision ID: faf2dbe4efc3
Revises: bf15b9bd23b8
Create Date: 2021-03-25 19:43:29.206394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'faf2dbe4efc3'
down_revision = 'bf15b9bd23b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'issue_date')
    op.drop_column('transactions', 'return_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('return_date', mysql.DATETIME(), nullable=True))
    op.add_column('transactions', sa.Column('issue_date', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
